Labels = [   
    'basket_bin',\
    'bed',\
    'bench',\
    'cabinet',\
    'call_bell',\
    'cane_stick',\
    'chair',\
    'door',\
    'electric_socket',\
    'fan',\
    'fire_extinguisher',\
    'handrail',\
    'human_being',\
    'rack',\
    'refrigerator',\
    'shower',\
    'sink',\
    'sofa',\
    'table',\
    'television',\
    'toilet_seat',\
    'walker',\
    'wardrobe',\
    'water_dispenser',\
    'wheelchair'
    ]
